version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lobo
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lobo
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha

  usuarios-service:
    build: ./usuarios-service
    ports:
      - "8081:8081"
    depends_on:
      - db
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lobo
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  ocorrencias-service:
    build: ./ocorrencias-service
    ports:
      - "8082:8082"
    depends_on:
      - db
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lobo
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - usuarios-service
      - ocorrencias-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/

